# Generated by Django 3.1.2 on 2020-10-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('jobtitle', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('user_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('total_time', models.IntegerField(null=True)),
                ('total_number_interviews', models.IntegerField(null=True)),
                ('has_live_coding', models.BooleanField(default=False)),
                ('has_pair_programming', models.BooleanField(default=False)),
                ('has_take_home', models.BooleanField(default=False)),
                ('can_meet_team', models.BooleanField(default=False)),
                ('got_an_offer', models.BooleanField(default=False)),
                ('would_recommend', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.position')),
            ],
        ),
    ]
